### ISSUE TITLE
Can't figure out how to?

### ISSUE THREAD

**Issue by susan3333333** [Eno-gamer10/Craft-Creator#1]
How do I make an "accept any" type recipe?

Like accept any item that has the forge tag egg, so it would accept minecraft egg, modded eggs, etc...for the same output?
Or, any stone, any wood/plank/whatever...

**Comment by En0ri4n** [comment]
Hello, thanks for the report, this feature will happen, i'm working on it ! :)

**Comment by susan3333333** [comment]
Awesome :) Thanks

**Comment by En0ri4n** [comment]
I forgot to ask you which version you are using (I forgot to ask you which version you are using (even though I am updating for all versions)

**Comment by susan3333333** [comment]
Hi, I am on 1.16.5 of minecraft :)

**Comment by En0ri4n** [comment]
The new version is released @susan3333333 !
I update the mod in 1.16.5, and added tag feature !

**Comment by En0ri4n** [comment]
The new version is released @susan3333333 !
I update the mod in 1.16.5, and added tag feature !

**Comment by susan3333333** [comment]
Thank you, it's working perfectly.
Tho, it did take me a moment to figure it out, as the instructions don't pop up unless u hold shift or control while on a square, LOL.

Thanks again :) This is such a needed mod.

**Comment by En0ri4n** [comment]
Yes it's true, I hesitated to put it at the bottom left still visible but I found better like that
