### ISSUE TITLE
NBT recipes??

### ISSUE THREAD

**Issue by susan3333333** [Eno-gamer10/Craft-Creator#3]
I have mods that add water cans, oil cans and other "refillables"
How do I make recipes for filling them?

**Comment by En0ri4n** [comment]
Recipes for which craft ? Do you talk about the fluid transposer from Thermal Mods ?

**Comment by susan3333333** [comment]
hardcore torch oil can, various mods watering cans etc....the recipe is for the crafting table, it fills the containers up varying amounts

**Comment by En0ri4n** [comment]
Okay, i see, I will try to add nbt support in crafts in the futur changes, thanks for the issue ! :)
Don't hesitate to tell me if i miss something else 👍 

EDIT: on which version are you ?

**Comment by susan3333333** [comment]
Currently 1.16.5 of Minecraft, tho dabbling in higher....

**Comment by En0ri4n** [comment]
I'm sorry but I think I'm not going to make any more updates for 1.16.5, there are too many different changes between java 8 and java 17 and between 1.16.5 and 1.18.2.
The available versions will be 1.18.2+, and I know if you started making a modpack in 1.16.5 you can't change so good luck anyway!
But in newer versions there will be nbt supports

**Comment by En0ri4n** [comment]
I lied, there will be a 1.16.5 version.

**Comment by En0ri4n** [comment]
Done in commit [Fixed crafting table recipe nbt issues](https://github.com/En0ri4n/Craft-Creator/commit/3a861c8f50868ece91067f50273894aed760f3a2)
