### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by wraithhawit** [Eno-gamer10/Craft-Creator#4]
my game crashes every time I mouse over the crafting table recipes. doesn't happen over any other kind of recipes. my current version of minecraft is 1.16.5 and mod version is 1.1.0

[crash-2023-01-16_11.12.23-client.txt](https://github.com/En0ri4n/Craft-Creator/files/10427991/crash-2023-01-16_11.12.23-client.txt)

**Comment by En0ri4n** [comment]
I'm sorry but i discontinued the version 1.16.5 of the mod because it was very difficult to make 1.16.5 and 1.18.2 simultaneously so i decided to just continue with 1.18.2+
