### ISSUE TITLE
[1.18.2] Crash when installed on Server

### ISSUE THREAD

**Issue by MokahTGS** [Eno-gamer10/Craft-Creator#8]
This crashes when it is in the mod folder on a server.  I understand that this is a client mod but it makes it difficult to use for modpack creation when you have to have different modpacks for making recipes and testing the modpack in a server environment.

**Comment by En0ri4n** [comment]
Hello,
can you provide the logs please ?

**Comment by MokahTGS** [comment]
sorry, crash logs from server: https://pastebin.com/NBYDKq2G

**Comment by En0ri4n** [comment]
It's my fault, i didn't think that people can use the mod on server, it may need some changes to work on server as well, I will work on it

**Comment by MokahTGS** [comment]
Thanks!  Makes for a much better testing environment for modpack creators.  Great mod BTW!  Can't wait for new additions!

**Comment by En0ri4n** [comment]
Fixed in 0235070a79889731577a77dc734166849a10f6a0
