### ISSUE TITLE
Crash when try to see the create mod crafting on the "K" menu

### ISSUE THREAD

**Issue by Edua2007** [Eno-gamer10/Craft-Creator#9]
Every time i try to open the create mod "K" menu to delete a recipe the game crash

LOG:
[latest.log](https://github.com/En0ri4n/Craft-Creator/files/11644722/latest.log)

CRASH:
[crash-2023-01-11_14.41.39-fml.txt](https://github.com/En0ri4n/Craft-Creator/files/11644723/crash-2023-01-11_14.41.39-fml.txt)

**Comment by En0ri4n** [comment]
Fixed in ba47fc1, I was using and old version of create, now it's good and a new version has been released on Curseforge

Thanks for the issue :)
